server:
  port: 0
  host: localhost
spring:
  active: dev
  cloud:
    config:
      url: http://localhost:8888
      name: chat-service
    eureka:
      url: http://localhost:8000
  datasource:
    mongoose:
      url: ''
